apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  type: NodePort
  selector:
    app: MyApp
  ports:
   - protocol: TCP
     port: 80
     targetPort: 80

---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: MyApp
spec:
  containers:
   - name: nginxpodcont
     image: nginx
     ports:
      - containerPort: 80

---
apiVersion: v1
kind: Pod
metadata:
  name: httpd-pod
  labels:
    app: MyApp
spec:
  containers:
   - name: httpd-pod-cont
     image: httpd
     ports:
      - containerPort: 80
