kind: Service
apiVersion: v1  ## kubectl api-resources 
metadata:
  name: np-svc1
  namespace: default 
spec:
  type: NodePort # Publishes a Nodeport on every Node in the cluster, and also creates an interbal Virtal LB and fwds requests into multiple backend pods
  selector: 
    type: app   # this is the labels of the pods which will be the backends,
  ports:
    - port: 80  ## this is your Virtual LB port 
      targetPort: 3000  ## this is the port inside cont

