kind: Pod  ## kubectl api-resources
apiVersion: v1
metadata:
  name: testpod1
  namespace: team-a
  labels:    ## defining a label for a is mandatory, with labels we can identify a group of similar pods
    team: toshiba    ## here both key & value are your choice
spec:  ## is about what is inside the pod
  containers:
    - name: container1
      image: 79man/samplepyapp:v1
      ports:
        - name: http
          containerPort: 3000
        - name: https
          containerPort: 3443

